/* 
 * handlers.h
 * by WN @ May. 27, 2010
 */

/* this file is used for being included into other .c or .h file */

def_handler(fstat64)
def_handler(mmap2)
def_handler(write)
def_complex_handler(exit_group)
def_complex_handler(exit)
def_complex_handler(rt_sigprocmask)
def_handler(sigprocmask)
def_trivial_handler(getpid)
def_trivial_handler(kill)
def_complex_handler(rt_sigaction)
def_handler(nanosleep)
def_trivial_handler(gettid)
def_trivial_handler(tgkill)
def_handler(brk)
def_trivial_handler(open)
def_trivial_handler(close)
def_handler(stat64)
def_handler(read)
def_handler(munmap)
def_handler(futex)
def_handler(ioctl)
def_handler(time)
def_handler(_llseek)
def_handler(socketcall)
def_handler(uname)
def_handler(mprotect)
def_handler(fcntl64)
def_handler(_newselect)
def_handler(clock_getres)
def_handler(clock_gettime)
def_trivial_handler(utime)
def_trivial_handler(getuid32)
def_handler(getcwd)
def_trivial_handler(geteuid32)
def_trivial_handler(getegid32)
def_trivial_handler(getgid32)
def_handler(ugetrlimit)
def_handler(poll)
def_handler(pipe)
def_complex_handler(clone)
def_handler(waitpid)
def_trivial_handler(writev)
def_handler(getdents64)
def_trivial_handler(epoll_create)
def_trivial_handler(epoll_ctl)
def_handler(epoll_wait)
def_trivial_handler(set_robust_list)
def_trivial_handler(madvise)
def_trivial_handler(setrlimit)
def_handler(gettimeofday)
def_handler(pread64)
def_trivial_handler(mkdir)
def_trivial_handler(setsid)
def_trivial_handler(umask)
def_trivial_handler(dup2)
def_trivial_handler(pwrite64)
def_handler(prctl)
/* rt_sigsuspend is NONTRIVIAL!
 * see correct_sigsuspend in arch_signal.c */
def_trivial_handler(rt_sigsuspend)
def_trivial_handler(sendfile64)
def_handler(setitimer)
def_trivial_handler(unlink)

// vim:ts=4:sw=4

